feat: refactor codebase and cleanup
elixir-cloud-aai/TESK pull request #171
Opened 2024-05-11 08:21 UTC by JaeAeich

## Description
Refactor code base and cleanup.

fixes - #152

2024-05-11 08:45 UTC, JaeAeich commented
@uniqueg as [discussed](https://github.com/elixir-cloud-aai/TESK/issues/152#issuecomment-2104513608), naming `src/tesk_core` to `tesk/service` would make sense, but wouldn't that steer away from  naming convention followed for released of modules, or will we keep the same name for the docker images (`tesk-core`) and just change the name in the code base (service)?

2024-05-11 09:29 UTC, JaeAeich commented
everything seems to work post python version 3.11, I'll shift make name change, ie src->tesk at least, rest need to be discussed.

2024-05-11 10:59 UTC, uniqueg requested changes

2024-05-11 10:59 UTC, uniqueg commented on MANIFEST.in
> +# TODO: Remove and add in `pyproject.toml`
Please create issues instead of `TODO`s (or update an existing related issue, e.g., add a check box). Let's keep the work that is left to do in one place. Goes for all `TODO`s.

2024-05-11 10:59 UTC, uniqueg commented on README.md
> +<img src="deployment/documentation/img/TESKlogowfont.png" height="200">
I'm not sure the TESK logo is a deployment artifact. To be consistent with [proTES](https://github.com/elixir-cloud-aai/proTES), I would put these files in `images/` in the root directory.

2024-05-11 10:59 UTC, uniqueg commented on README.md
> +An implementation of a task execution engine based on the [TES standard](https://github.com/ga4gh/task-execution-schemas) running on `Kubernetes`. For more details on `TES`, see the (very) brief [int
I'm not sure the TES intro is a deployment artifact. To be consistent with other projects (e.g., [FOCA](https://github.com/elixir-cloud-aai/foca)), I would put such additional docs that we do not want to put in `README.md` into a `docs/` folder in the root directory. Put _only_ the deployment docs in `deployment/`.

2024-05-11 10:59 UTC, uniqueg commented on deployment/charts/tesk/.gitignore
I think it would be better to remove this file and merge it's contents into `.gitignore` in the root directory.

2024-05-11 10:59 UTC, uniqueg commented on deployment/examples/inputFile.json
Are the examples only used by (and useful for) people deploying the service? If they are _also_ useful for users/clients, keep them in `examples/` in the root folder, or, perhaps better, move them to `docs/examples`.

Let's try to keep the deployment strictly separate from the app.

2024-05-11 10:59 UTC, uniqueg commented on tesk/tesk_core/README.md
As discussed, I would rename `src/tesk_core/` to `tesk/services/` though you can also do that later if you like.

2024-05-11 10:59 UTC, uniqueg commented on Makefile
This is quite neat and cleans up a lot of files. However, let's see what @lvarin etc. think about this, as I cannot imagine what consequences merging all these scripts has (if any).

2024-05-11 10:59 UTC, uniqueg commented on tests/unit_test/service/FilerClassTest.py
For consistency, perhaps better call the directory `tests/test_unit` rather than `tests/unit_test`

2024-05-11 18:14 UTC, uniqueg commented
Also, why are Python 3.8, 3.9 and 3.10 failing, @JaeAeich?

On the other hand, it's not clear to me why we are even testing multiple Python versions, TESK is not a library. We pick one version and use that version, no need to support multiple Python versions...

2024-05-11 18:27 UTC, JaeAeich commented
> Also, why are Python 3.8, 3.9 and 3.10 failing, @JaeAeich?
> 
> On the other hand, it's not clear to me why we are even testing multiple Python versions, TESK is not a library. We pick one version and use that version, no need to support multiple Python versions...

I have no idea, lack of backwards compatibility ig, I haven't touched any code of tesk_core yet. Should I free python version to 3.11 and above (for pyproject.toml)? Will remove the other versions from API.

Also core seems to use kubernetes client v9 and rn its on v29 :face_in_clouds: , I'll definetely have to refactor core code as well in order to start to use same k8s client version on api.

2024-05-14 13:42 UTC, JaeAeich commented
IG, changing the name of github actions workflow (to comply with other file name and repos) tripped it and its not showing tests, but all the tests passed. You can check it as well and I have simulated in on a clean ubuntu docker image just to be sure :)

2024-05-15 07:43 UTC, trispera commented on Makefile
> +			--format=docker \
I think we can edit `--format=docker` to `--format=oci`
Our new container platform at CSC supports the last format and most of the images on DockerHub will be forced to `oci` in the future.
https://docs.docker.com/engine/deprecated/#pushing-and-pulling-with-image-manifest-v2-schema-1

2024-05-15 10:50 UTC, uniqueg commented
> IG, changing the name of github actions workflow (to comply with other file name and repos) tripped it and its not showing tests, but all the tests passed. You can check it as well and I have simulated in on a clean ubuntu docker image just to be sure :)

I think you need to update the test names in the branch protection rules. If you don't have the permissions (which I think you do) I'll do it when reviewing tomorrow.

2024-05-16 04:18 UTC, JaeAeich commented
> which I think you do

I don't have 'em! I don;t see branch protections rules in [settings](https://github.com/elixir-cloud-aai/TESK/settings) :cry: .

2024-05-16 07:32 UTC, JaeAeich commented
Hey there are some TODOs that I'll take care in this PR itself, please ignore those and review the rest :)

2024-05-18 10:15 UTC, uniqueg commented
> Hey there are some TODOs that I'll take care in this PR itself, please ignore those and review the rest :)

They're here: https://github.com/elixir-cloud-aai/TESK/settings/branches

You need to edit the rule for branch `main`, then under "Require status checks to pass before merging" you need to use the search box to add the checks by name, e.g., "code-vulnerabilities" or "Semantic PR title".

Anyway, I have done that now in case you don't have access to that setting.

2024-05-18 11:28 UTC, JaeAeich commented
Yeah I don't have the rights, but thanks for updating it :)

2024-05-18 11:30 UTC, uniqueg requested changes
Amazing job @JaeAeich. Of course the PR is waaay too big to review in depth (and also it's not always clear what was new code and what was just renamed but not picked up by the system, e.g., TESK-core code and corresponding tests). But I understand that this was +/- necessary to keep tests passing (which is commendable). Still, in the future, I hope we will get small, iterative PRs ;-)

Anwyay, I suggest that after addressing (or acknowledging and potentially creating issues for the future) the comments and a final review, we should be good to go for merging. There are likely still several issues (mostly legacy ones), but we can address them iteratively.

2024-05-18 11:30 UTC, uniqueg commented on Makefile
> +# TODO: Add commands to be compatible for windows
I really don't think we need to worry about Windows :)

2024-05-18 11:30 UTC, uniqueg commented on deployment/containers/filer.Dockerfile
Following up from the comment above: Check if you can have multiple `.dockerignore` files. If so, prepare one `.dockerignore` file specific to each `Dockerfile`.

2024-05-18 11:30 UTC, uniqueg commented on tesk/service/__init__.py
> +_summary_:service (tesk_core) package initialization file.
I would completely remove any mention of `test_core`

2024-05-18 11:30 UTC, uniqueg commented on tesk/__init__.py
> +_summary_:tesk package initialization file.
You could use Sphinx references to create linked API docs later on. For example, you could make use of `:currentmodule::` here. And similarly, use `:mod:`, `:class`, `:meth`, `:func` in your docstrings, where appropriate.

But no need to do this now, just FYI for the future.

2024-05-18 11:30 UTC, uniqueg commented on tests/test_unit/service/resources/copyDirTest/dst2/a/1.txt
For consistency (and to avoid confusion), add `test_` to every test Python module or package name, so rename this to:
`tests/test_unit/test_service/resources/copyDirTest/dst2/a/1.txt`

2024-05-18 11:30 UTC, uniqueg commented on pyproject.toml
> +description = "An implementation of a task execution engine based on the TES standard running on Kubernetes."
Better: "[...] on the GA4GH Task Execution Service (TES) API standard [...]"

2024-05-18 11:30 UTC, uniqueg commented on pyproject.toml
> +    "Programming Language :: Python :: 3.13",
Consider removing (compare comment above and discussion elsewhere).

2024-05-18 11:30 UTC, uniqueg commented on pyproject.toml
> +maintainers = ["TBA <you@example.com>", "TBA <you@example.com>"]
Put `cloud-service@elixir-europe.org` for both.

2024-05-18 11:30 UTC, uniqueg commented on pyproject.toml
> +    "Development Status :: 4 - Alpha",
I think this should be at least `Beta` by now :)

2024-05-18 13:35 UTC, JaeAeich commented
We need `codecov` token, and helm CI is not running, we need to test that as well, I have broken that into multiple jobs to comply with a "consistency".

Apart from that since this PR has grown big enough why not discuss some extra things I found while studying other repos and etc etc.

- Consider adding [DCO](https://github.com/apps/dco) check in CI.
- Consider adding OSS licence compliance that shows that well what is say :), we can add its card to the readme as well with codecov, coverage.

2024-05-18 13:43 UTC, uniqueg commented
> We need `codecov` token, and helm CI is not running, we need to test that as well, I have broken that into multiple jobs to comply with a "consistency".
> 
> Apart from that since this PR has grown big enough why not discuss some extra things I found while going through other repos and etc etc.
> 
> * Consider adding [DCO](https://github.com/apps/dco) check in CI.
> * Consider adding [OSS licence compliance](https://fossa.com/pricing) (license scan seems to be free 🤞 ) that shows, well what is says :), we can add its card to the readme as well with codecov, coverage.

Sure, feel free to add (low priority) issues for these :)

2024-05-18 13:49 UTC, uniqueg commented
> We need `codecov` token, and helm CI is not running, we need to test that as well, I have broken that into multiple jobs to comply with a "consistency".
> 
> Apart from that since this PR has grown big enough why not discuss some extra things I found while going through other repos and etc etc.
> 
> * Consider adding [DCO](https://github.com/apps/dco) check in CI.
> * Consider adding [OSS licence compliance](https://fossa.com/pricing) (license scan seems to be free 🤞 ) that shows, well what is says :), we can add its card to the readme as well with codecov, coverage.

`CODECOV_TOKEN` is now set for this repo. Not sure what you need for the Helm CI, but I think we should merge this ASAP before it gets even more unwieldy. I propose that you remove the part that installs the chart for now (we can get it back from `master` later on), which is likely the one that fails at the moment? Or even remove the entire workflow.

2024-05-18 13:57 UTC, uniqueg requested changes
We're getting there, just a few small issues before we can merge.

However, sth is weird about your Git workflow. Several (but not all) files are shown here as completely new, even though there were just moved or a few lines were changed (e.g., `pyproject.toml`, some but not all test files moved from `service` to `test_service`). Try to figure out why that is and avoid it in the future, because it makes things hell to review and also you `git blame` will show you as the author of all of that code, even if you are not.

2024-05-18 13:57 UTC, uniqueg commented on test_unit
What is this? Probably should be removed or included in `.gitignore`

2024-05-18 13:57 UTC, uniqueg commented on test_unit.xml
Add to `.gitignore`?

2024-05-19 05:31 UTC, JaeAeich commented
> We're getting there, just a few small issues before we can merge.
> 
> However, sth is weird about your Git workflow. Several (but not all) files are shown here as completely new, even though there were just moved or a few lines were changed (e.g., `pyproject.toml`, some but not all test files moved from `service` to `test_service`). Try to figure out why that is and avoid it in the future, because it makes things hell to review and also you `git blame` will show you as the author of all of that code, even if you are not.

I don't think there is anything wrong with my workflow, the issue was that the code files were not formatted at all and had inconsistent spacing even between two words :sweat_smile: , plus fixing some minor issues to comply with Google's python coding guide like changing string concatenation to f string, these kind of small fixes were cluttered all around the code base. I believe that is the cause of this weird blame thing. But if it happens again I'll be sure to check into it :)

2024-05-19 05:39 UTC, JaeAeich commented
@uniqueg can you please give me codecov badge from [here](https://app.codecov.io/gh/elixir-cloud-aai/TESK/settings/badge) (supposedly :crossed_fingers: ).

2024-05-19 11:26 UTC, uniqueg approved these changes
LGTM, I'm gonna merge. From now on please keep the PRs small and semantic

2024-05-19 11:34 UTC, merged