feat: add `sphinx` and configure `readthedocs`
elixir-cloud-aai/TESK pull request #177
Opened 2024-05-21 12:20 UTC by JaeAeich

Add `sphinx` (theme furo) and configure `readthedocs`. Also link existing docs to be create a landing page of sorts.

fixes - #166

2024-05-21 12:23 UTC, JaeAeich commented on docs/make.bat
> +@ECHO OFF
I'll remove this file, I remember @uniqueg's last review that, we aren't conserned about windows :)

2024-05-21 12:26 UTC, JaeAeich commented on docs/conf.py
> +copyright = f"{current_year}, {str(pkg_meta['authors'][0])}"
Nah, better this way, I prefer to keep `pyproject` the "single" source of truth :+1:

2024-05-21 13:31 UTC, uniqueg commented on docs/conf.py
> +# Configuration file for the Sphinx documentation builder.
On that note, please add `flake8-docstrings` and potentially `flake8-docstrings-complete`. We indeed want to have (Google-style) docstrings for every package, module, class, function and method.

2024-05-23 08:34 UTC, JaeAeich commented on tesk/services/README.md
created a simlink to get readme preview on gh.

2024-05-23 08:34 UTC, JaeAeich commented on tesk/__init__.py
>  """
added `pydocstyle`, see above.

2024-05-23 08:36 UTC, JaeAeich commented on docs/tesk/modules.rst
I wanna add this stuff to `precommit` and all that is `auto-generated`. We could specify different outputs but this is the simplest way IMO which will take care or any future code changes or even restructures :)

2024-05-23 08:38 UTC, JaeAeich commented on README.md
> +An implementation of a task execution engine based on the [TES standard](https://github.com/ga4gh/task-execution-schemas) running on `Kubernetes`. For more details on `TES`, see the (very) brief [int
yeah I did try `pages` and `pages/tesk` for some reason they looked odd to me so I switched it to `tesk` but I guess better follow the convention.

2024-05-23 09:13 UTC, JaeAeich commented on pyproject.toml
> +furo = "^2024.5.6"
I wanted to create a "mega" dep group that people can install all `dev` deps in a go, but now that I think of it, it goes against `install --with` option of `poetry`, and we might not have a use case of such.

But if you see, main deps and `test` deps share a common dep, so maybe I should fix this all in a different PR. I am removing just `docs` deps from `dev` in this PR.

2024-05-23 09:22 UTC, JaeAeich commented on pyproject.toml
> +furo = "^2024.5.6"
Oh! CI change wasn't needed!
#180

2024-05-23 09:23 UTC, JaeAeich commented
@uniqueg please configure readthedocs on `main`, it should generate a link for us to review in this PR itself if I'm not wrong :thinking: .

2024-05-23 12:40 UTC, JaeAeich commented on docs/static_docs/README.md
Heyyyy!!!! why is this showing up :sob: , does creating a `symlink` cause this??

2024-05-23 12:42 UTC, JaeAeich commented on docs/conf.py
> +# Configuration file for the Sphinx documentation builder.
it had `~300` error, I have fixed all those I could in this PR and ignored major ones like, missing `docstring` etc etc :+1:

2024-05-24 04:43 UTC, JaeAeich commented on docs/static_docs/README.md
They were absolute symlinks :man_facepalming: .

2024-05-24 11:31 UTC, uniqueg commented on docs/tesk/modules.rst
Well, obviously the API docs should be auto-generated. But you should be able to specify the target folder. I'm fine with `docs/API/tesk` being the root, but we shouldn't just dump everything in the root `docs` dir.

2024-05-24 11:46 UTC, uniqueg requested changes
@JaeAeich Small, iterative changes, please!! 🙈

Most of the changes here have nothing to do with Sphinx/RTD. Please split this up into multiple PRs. One of Sphinx/RTD. One for docstrings. One for wording changes. One for formatting changes.

It may seem like an overhead to you, but it will actually increase the turnaround. I will not approve non-semantic or messy PRs. Yes, that means that the initial docs will not be as beautiful as they could be. But that's fine, we _want_ them to improve iteratively.

2024-05-24 11:46 UTC, uniqueg commented on docs/static_docs/deployment.md
> +a point of reference.
Please focus on the _minimal_ changes required to address a given issue. This (and other) changes have nothing to do with Sphinx or Read the Docs. We want our commits to be sematic so that we can read it and understand where what was changed. And we want there to be many iterative commits. Lumping everything together also makes it a real pain to review. 

I can just about live with changes to the structure of the `docs` directory while you are at it (even though those are also not strictly required to add Read the Docs support). But please don't include changes to the wording or format, that should happen in other commits.

2024-05-24 11:46 UTC, uniqueg commented on tesk/services/exceptions.py
> +	----------
Please use Google-Style docstrings. But _not in this PR_!!

2024-05-24 12:16 UTC, JaeAeich commented
Ill create another PR on top of it to add RTD and sphinx.

2024-05-24 12:25 UTC, JaeAeich commented on docs/static_docs/deployment.md
> +a point of reference.
I tried to do `.. mdinclude ::` in `index.rst` file from their original places, ie. `deployment/docs` which I agree made more sense but I can't seem to get it running like that unfortunately, IDK if its the plugins fault or I am missing something I tried to do it for quite sometimes, then I decided if I have to include all the documentation in `RTD` I will have to do it.

Can you check it out or have a way to make it work from their original location :thinking: ? What to do?

2024-05-27 08:17 UTC, JaeAeich commented on docs/tesk/modules.rst
I have removed docs stuff from this PR.

2024-05-27 08:17 UTC, JaeAeich commented on docs/static_docs/deployment.md
> +a point of reference.
I have removed docs stuff from this PR.

2024-05-28 16:58 UTC, uniqueg requested changes
We're getting there, but still plenty of changes that don't have anything to do with the PR topic.

2024-05-28 16:58 UTC, uniqueg commented on .editorconfig
What is this used for? If it's for code editors, sure this should be in version control (given that different people may use different editors)? In any case, the change doesn't seem to be concerned with `pydocstyle`.

2024-05-28 16:58 UTC, uniqueg commented on Makefile
Change doesn't seem to be concerned with `pydocstyle`

2024-05-28 16:58 UTC, uniqueg commented on README.md
Changes don't seem to be concerned with `pydocstyle`

2024-05-28 16:58 UTC, uniqueg commented on deployment/documentation/deployment.md
Changes don't seem to be concerned with `pydocstyle`

2024-05-28 16:58 UTC, uniqueg commented on deployment/documentation/local_ftp.md
Changes don't seem to be concerned with `pydocstyle`

2024-05-28 16:58 UTC, uniqueg commented on docs/tesintro.md
Changes don't seem to be concerned with `pydocstyle`

2024-05-28 16:58 UTC, uniqueg commented on pyproject.toml
> +api = 'tesk.api.app:main'
Change doesn't seem to be concerned with `pydocstyle`

2024-05-28 16:58 UTC, uniqueg commented on tesk/services/__init__.py
> +"""service package initialization file."""
Either capitalize or use code syntax highlighting (or better yet, a package reference) for Sphinx and write `services` (plural) to match the name of the package.

Also note that this is actually the docstring for the entire _package_, not just the init file.

Same applies to other module-level docstrings.

2024-05-28 16:58 UTC, uniqueg commented on tesk/services/constants.py
> +"""The constants used in the services module."""
It's for the `services` package. Please use Sphinx-style code highlighting or package cross-reference.

2024-05-28 16:58 UTC, uniqueg commented on tesk/services/filer.py
> +	"""https://stackoverflow.com/a/12514470/1553043."""
I'm not sure if you want to use this PR to write _good_ docstrings for classes, methods and functions that we won't have to change later on, or whether it's just enough to satisfy `pydocstyle`. I would be okay with both, but given that there will likely be many changes still in these files over the next couple of weeks/month, possibly with many classes/methods/functions disappearing or significantly changing, I would tend to just do the latter. And in accordance with that, I will not review the docstrings (only module- and package-level ones, because I don't think they will change much at this point).

2024-05-28 16:58 UTC, uniqueg commented on tests/test_unit/test_services/FilerClassTest.py
> +					#  claimName: task-pv-claim.
Change doesn't seem related to `pydocstyle`.

2024-05-28 16:58 UTC, uniqueg commented on tests/test_unit/test_services/test_filer.py
> +        """),
Changes don't seem related to `pydocstyle`.

2024-05-28 16:58 UTC, uniqueg commented on tests/test_unit/test_services/test_filer.py
> +        """),
Changes don't seem related to `pydocstyle`.

2024-05-28 16:58 UTC, uniqueg commented on tests/test_unit/test_services/test_s3_filer.py
> +			"""
Changes don't seem related to `pydocstyle`.

2024-05-28 16:58 UTC, uniqueg commented on tests/test_unit/test_services/test_s3_filer.py
> +			"""
Changes don't seem related to `pydocstyle`.

2024-05-28 16:58 UTC, uniqueg commented on tests/test_unit/test_services/test_s3_filer.py
> +				"""
Changes don't seem related to `pydocstyle`.

2024-05-30 05:09 UTC, JaeAeich commented on .editorconfig
yeah its a way to standardise all editors settings for a project, it intergrates with almost all editors. I put it there because I think we should have such settings. Maybe in another PR. Ill remove it.

2024-05-30 05:27 UTC, JaeAeich commented
@uniqueg Since this PR dealt with alot of stuff initially, hunting down and reverting all the stuff seems little hard, its easier to make a new one. I am closing this PR, please review the new ones, where I have only added pydocstyle and ignore all the rest.

2024-05-30 05:27 UTC, closed without merging