feat(ci): cache
elixir-cloud-aai/TESK pull request #178
Opened 2024-05-21 12:53 UTC by JaeAeich

cache invalidation in github actions

fixes - #174

2024-05-21 12:54 UTC, JaeAeich commented
PS: not completed and not converting to draft because need to test CI :)

2024-05-21 12:56 UTC, JaeAeich commented on .github/workflows/code_quality.yaml
> +        id: cq
no :face_in_clouds:

2024-05-21 12:57 UTC, JaeAeich commented on .github/workflows/code_quality.yaml
> -        run: pipx install poetry
Aah yesss my AI overlord, forgive me for I have fallen :disappointed:!

2024-05-23 12:56 UTC, uniqueg requested changes
Great stuff! I'm on my phone so it's a bit hard to review all details. But since it runs fine, I think it should be good. Two minor things, one maybe an oversight, the other a matter of opinion, I guess.

2024-05-23 12:56 UTC, uniqueg commented on .github/workflows/code_test_unit.yaml
>        - name: Set up Python
Shouldn't we remove this here? I think it's already part of the Poetry action

2024-05-23 12:56 UTC, uniqueg commented on .github/actions/setup/poetry/action.yaml
> +name: Setup Python and Poetry Action
Would it not make sense to add checkout to the composite action as well? Seems to me that in every job where we use this action, checkout immediately proceeds it, and I have a hard time imagining a scenario where we would need this action _without_ checking out the repository. Both are basically essential parts of "setting up the environment". And it would save two lines of redundant code for each job...

2024-05-24 04:25 UTC, JaeAeich commented on .github/actions/setup/poetry/action.yaml
> +name: Setup Python and Poetry Action
Aah! actually even if I added that to poetry setup action I would still need to checkout the repo because the action  is in the repo itself, `gh-actions` doesn't know about the whole action thing unless it checks it out.

2024-05-24 11:48 UTC, uniqueg approved these changes

2024-05-24 11:59 UTC, merged